# Generated by Django 3.2.8 on 2021-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='perfil_professor',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_postagem',
            field=models.DateField(verbose_name='Data da postagem'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
