# Generated by Django 3.1.2 on 2022-02-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_aluno',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_aluno',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_aluno',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.turma'),
        ),
        migrations.AlterField(
            model_name='perfil_professor',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_professor',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_professor',
            name='titulacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulação'),
        ),
    ]
