# Generated by Django 3.2.8 on 2021-12-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20211202_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da postagem'),
        ),
    ]
