# Generated by Django 3.2.8 on 2022-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20220206_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_aluno',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='perfil_professor',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.AddField(
            model_name='perfil_aluno',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='perfil_professor',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
