# Generated by Django 3.2.8 on 2022-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20220209_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_aluno',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfil_aluno',
            name='nome_completo',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='perfil_professor',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfil_professor',
            name='nome_completo',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome Completo'),
        ),
    ]
